import { useState } from "react";
import { useNavigate } from "react-router-dom";

import { calculatePadding } from "../../utils/padding";
import { binaryString } from "../../utils/binary";
import { generateMessageSchedule } from "../../utils/messageSchedule";
import { INITIAL_HASH } from "../../utils/constants";
import { calculateCompressionRounds } from "../../utils/compressionRounds";
import { calculateFinalHash } from "../../utils/finalHash";

import "./FinalHashStep.css";


type Props = {
    input: string;
};


export default function FinalHashStep({ input }: Props) {

    const navigate = useNavigate();

    const [
        showRevertExplanation,
        setShowRevertExplanation
    ] = useState(false);


    const binary = binaryString(input);

    const padding = calculatePadding(binary);

    const words = generateMessageSchedule(
        padding.finalBlock512
    );

    const compressionResult =
        calculateCompressionRounds(
            INITIAL_HASH,
            words
        );

    const finalHash =
        calculateFinalHash(
            INITIAL_HASH,
            compressionResult.finalWorkingVariables
        );


    return (

        <div className="final-hash-step">

            <h2>
                Final Hash
            </h2>


            {/* Final hash */}

            <div className="choose-instruction-card">

                {finalHash.hex}

            </div>


            {/* Explanation */}

            <p className="final-hash-description">

                This is the final 256-bit digest
                generated by SHA-256 from your input.

            </p>


            {/* Actions */}

            <div className="digest-actions">

                <button
                    className="digest-primary-button"
                    onClick={() =>
                        setShowRevertExplanation(true)
                    }
                >
                    ↶ Try to Revert
                </button>


                <button
                    className="digest-primary-button"
                    onClick={() =>
                        navigate("/posttest")
                    }
                >
                    Continue to Post-test
                    <span>→</span>
                </button>

            </div>


            {/* Revert explanation */}

            {showRevertExplanation && (

                <div className="revert-overlay">

                    <div className="revert-modal">

                        <button
                            className="revert-close"
                            onClick={() =>
                                setShowRevertExplanation(
                                    false
                                )
                            }
                        >
                            ×
                        </button>


                        <div className="revert-icon">
                            ↶
                        </div>


                        <p className="revert-eyebrow">
                            ONE-WAY FUNCTION
                        </p>


                        <h3>
                            Hashing cannot be reversed
                        </h3>


                        <p>
                            A cryptographic hash function
                            is designed to work in one
                            direction. The original input
                            cannot be recovered from the
                            hash value.
                        </p>


                        <div className="revert-comparison">

                            <div>

                                <span>
                                    Input
                                </span>

                                <strong>
                                    Message
                                </strong>

                            </div>


                            <div className="comparison-arrow">
                                →
                            </div>


                            <div>

                                <span>
                                    Hash
                                </span>

                                <strong>
                                    Digest
                                </strong>

                            </div>

                        </div>


                        <p className="revert-note">

                            This is different from
                            encryption, where encrypted
                            data can be decrypted using
                            the appropriate key.

                        </p>


                        <button
                            className="modal-button"
                            onClick={() =>
                                setShowRevertExplanation(
                                    false
                                )
                            }
                        >
                            Got it
                        </button>

                    </div>

                </div>

            )}

        </div>
    );
}